name: Check Google Drive for Updates

on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual trigger

jobs:
  check-drive:
    runs-on: ubuntu-latest  # You can change this to macos-latest or windows-latest if needed

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4  # Fetches the latest code

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"  # Specify the required Python version

      - name: Install Dependencies
        run: |
          python -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt

      - name: Run Check Drive Script
        run: |
          source venv/bin/activate
          python src/check_drive.py  # Update this with your actual script path

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: processed-data
          path: output/  # Ensure your script outputs data here

